version: '3.2'

services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

    server:
        build:
          context: ./server/
        env_file:
            - ./server/.env
        command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
        volumes:
            - ./server:/code
            - media:/media
        ports:
            - '8888:8000'
        depends_on:
            - db

    client:
        image: mhart/alpine-node
        command: sh -c 'yarn install && yarn start'
        env_file:
            - ./client/.env
        volumes:
            - ./client:/code
        ports:
            - '5000:5000'
        working_dir: /code

volumes:
  media:
  postgres-data:
