name: Kosh-App

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Test and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Deploy
              run: ./deploy/deploy.sh
              env:
                  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
                  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_TOKEN }}

