name: Kosh-App

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Test and Deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: deploy
        steps:
            - name: Test
              run: echo "Testing..."

            - name: Deploy
              run: ./deploy.sh

